server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # SPA: all routes fall back to index.html
    location / {
        try_files  / /index.html;
    }

    # Report images and Excel files proxied to backend
    location /static/ {
        proxy_pass http://backend:18080;
        proxy_set_header Host System.Management.Automation.Internal.Host.InternalHost;
        proxy_set_header X-Real-IP ;
    }

    # API proxy to backend
    location /api/ {
        proxy_pass http://backend:18080;
        proxy_set_header Host System.Management.Automation.Internal.Host.InternalHost;
        proxy_set_header X-Real-IP ;
        proxy_read_timeout 300s;
    }
}
